//
// Generated by RAGE Shader Editor 1.4.4
    ps_3_0
    def c219, 1.83951739e+025, 3.99382587e+024, 4.54357875e+030, 1.40129846e-045
    def c0, 0.5, 1, 0.25, 0
    def c1, 0.001, 0.5, 0.25, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0
    mov oC0.x, r0.x
    mad oDepth, r0.x, c1.x, c1.y
    mov oC0.yzw, c0.w

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
