//
// Generated by RAGE Shader Editor 1.4.4
    ps_3_0
    def c219, 1.83951739e+025, 3.99382587e+024, 4.54357875e+030, 1.14205825e-042
    def c127, 0.999999881, 1, 0, 0
    def c0, 58.1640015, 47.1300011, 0, 0
    def c1, 0, 0.212500006, 0.715399981, 0.0720999986
    def c2, 0.25, 1, 256, 0
    def c3, 0, 2, 4, 8
    def c4, -0.5, -1.5, 1.5, 0.5
    def c5, 2, -1, 0.125, 0
    def c6, 256, 2, 4, 8
    def c10, 1.33333325, 1.05263162, 1.05577004, 0.0762000009
    def c11, 0.0166666992, 0, 0, 0
    def c99, 0.00138889998, 0.0416667014, 0.666666687, 1080
    def c100, 1, 0, 0.707107008, 0.707107008
    def c101, -0, 1, -0.707107008, 0.707107008
    def c102, -1, -0, -0.707105994, -0.707107008
    def c103, 0, -1, 0.707107008, -0.707107008
    def c104, 2, 0, 1.84775996, 0.765366018
    def c105, 1.41421402, 1.41421402, 0.765366018, 1.84775996
    def c106, -0, 2, -0.765367985, 1.84775805
    def c107, -1.41421402, 1.41421402, -1.84775996, 0.765366018
    def c108, -2, -0, -1.84775805, -0.765367985
    def c109, -1.41421199, -1.41421402, -0.765366018, -1.84775996
    def c110, 0, -2, 0.765367985, -1.84775805
    def c111, 1.41421402, -1.41421402, 1.84775996, -0.765366018
    def c112, 3, 0, 2.89777803, 0.776457012
    def c113, 2.59807491, 1.5, 2.12132096, 2.12132096
    def c114, 1.5, 2.59807801, 0.776457012, 2.89777803
    def c115, -0, 3, -0.776457012, 2.89777803
    def c116, -1.5, 2.59807491, -2.12132096, 2.12132096
    def c117, -2.59807801, 1.5, -2.89777803, 0.776457012
    def c118, -3, -0, -2.89777803, -0.776459992
    def c119, -2.59807491, -1.5, -2.1213181, -2.12132096
    def c120, -1.49999702, -2.59807801, -0.776457012, -2.89777803
    def c121, 0, -3, 0.776457012, -2.89777803
    def c122, 1.5, -2.59807491, 2.12132096, -2.12132096
    def c123, 2.59807801, -1.49999702, 2.89777803, -0.776453972
    def c130, -1, 0, 1, 0
    def c131, 0.0121568628, 0.0160784312, 0.0435294099, 0.047450982
    def c132, 0.514117658, 0.518039227, 0.545490205, 0.549411774
    def c133, 0.0278431363, 0.000784313714, 0, 0
    //	def c144, 0.00390625, 0.3, -0.5, 0 // 1/256, valor perceptivel, 
    defi i1, 3, 0, 0, 0
    defi i0, 14, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s6
    dcl_2d s8
    dcl_volume s9
    
    mov r31, c1.x
    texld r0, v0, s1
    if_ne r0.x, c127.y
      rcp r20.x, c128.x
      mul r20.x, r20.x, c128.y
      pow r20.x, r20.x, r0.x
      mul r20.x, r20.x, c128.x
      add r20.y, r20.x, -c128.x
      add r20.z, c128.y, -c128.x
      mul r20.y, r20.y, c128.y
      mul r20.z, r20.z, r20.x
      rcp r20.z, r20.z
      mul r20.w, r20.y, r20.z
      min r0, r20.w, c127.x
    endif
    add r0.y, -c77.x, c77.y
    rcp r0.y, r0.y
    mul r0.z, r0.y, c77.y
    mul r0.z, r0.z, -c77.x
    mad r0.x, c77.y, -r0.y, r0.x
    rcp r0.x, r0.x
    mul r0.y, r0.z, r0.x
    mov r30.y, c223.z
    if_ne r30.y, c130.y
      mov r20, c130.y
      mov r21.xy, c130.x
      rep i1
        rep i1
          mad r22.xy, c76, r21.xyyy, v0
          texldl r22, r22, s6
          add r23, r22.x, -c131
          add_sat r23, -r23_abs, c133.y
          add r20, r20, r23
          add r23, r22.x, -c132
          add_sat r23, -r23_abs, c133.y
          add r20, r20, r23
          add r23, r22.x, -c133.x
          add_sat r23, -r23_abs, c133.y
          add r20, r20, r23
          add r21.y, r21.y, c130.z
        endrep
        mad r21.xy, r21.x, c130.zyyy, c130.zxxx
      endrep
      dp4 r30.x, r20, c130.z
    else
      mov r30.x, c130.z
    endif
    texld r1, v0, s2
    texld r2, v0, s3
    abs r0.w, c79.w
    mov r3, c4
    mad r4.xy, c76, r3, v0
    texld r4, r4, s2
    mad r5.xy, c76, r3.zxzw, v0
    texld r5, r5, s2
    mad r3.xz, c76.xyyw, r3.wyzw, v0.xyyw
    texld r6, r3.xzzw, s2
    mad r3.xy, c76, r3.ywzw, v0
    texld r7, r3, s2
    dp3 r1.w, r4, r4
    rcp r1.w, r1.w
    cmp r3.xyz, -r1_abs.w, c1.x, r4
    dp3 r1.w, r5, r5
    rcp r1.w, r1.w
    cmp r4.xyz, -r1_abs.w, c1.x, r5
    dp3 r1.w, r6, r6
    rcp r1.w, r1.w
    cmp r5.xyz, -r1_abs.w, c1.x, r6
    dp3 r1.w, r7, r7
    rcp r1.w, r1.w
    cmp r6.xyz, -r1_abs.w, c1.x, r7
    dp3 r1.w, r1, r1
    rcp r1.w, r1.w
    cmp r7.xyz, -r1_abs.w, c1.x, r1
    mad r0.x, r0.z, r0.x, -c78.w
    mad r0.x, c78.y, -r3.w, r0.x
    max r1.w, r0.x, c1.x
    rcp r0.x, c78.z
    mul r0.x, r1.w, r0.x
    lrp r1.w, r0.x, c79.z, c79.y
    min r0.x, c79.z, r1.w
    cmp r0.x, -c222.y, r31.x, r0.x
    dp3 r0.z, r7, c1.yzww
    dp3 r8.x, r3, c1.yzww
    dp3 r8.y, r4, c1.yzww
    dp3 r8.z, r5, c1.yzww
    dp3 r8.w, r6, c1.yzww
    dp4 r1.w, r8, c2.x
    add r8, r8, -r1.w
    dp4 r2.w, r8, r8
    add r0.z, r0.z, -r1.w
    mad r0.z, r0.z, r0.z, -r2.w
    mul r0.x, r0.x, r0.x
    cmp r0.z, -r30_abs.x, -c2.y, r0.z
    cmp r0.x, r0.z, c2.y, r0.x
    texld r8, v0, s0
    mov r8.yz, c2
    mad r9, r8.w, -r8.z, c3
    cmp r9, r9, c2.y, c2.w
    mad r10, r8.w, -c6.x, c6.yzwx
    cmp r10, r10, -c2.y, -c2.w
    add r9, r9, r10
    mul r9, r9, c1.x
    dp4 r0.z, r9, c2.y
    add r0.z, r0.z, c4.w
    rcp r0.z, r0.z
    mul r8.xzw, r3.xyyz, r9.x
    mad r7.xyz, r7, c4.w, r8.xzww
    mad r7.xyz, r4, r9.y, r7
    mad r7.xyz, r5, r9.z, r7
    mad r7.xyz, r6, r9.w, r7
    mul r7.xyz, r0.z, r7
    add r0.z, -r0.x, c2.y
    mul r1.w, r0.x, c2.x
    if_ne c222.y, r31.x
      mov r20.z, c79.z
      if_gt r20.z, c1.x
        mov r20, c99
        mov r21, c1.x
        mov r22, c76
        if_gt c44.y, r20.w
          mul r22, r22, r20.z
        endif
        mul r22, r22, c44.y
        mul r22, r22, r20.x
        mad r23.xy, r22, c100.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c100.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c101.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c101.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c102.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c102.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c103.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c103.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c104.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c104.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c105.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c105.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c106.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c106.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c107.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c107.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c108.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c108.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c109.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c109.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c110.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c110.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c111.xyyy, v0
        texldl r23, r23, s2
        add r21, r21, r23
        mad r23.xy, r22, c111.zwww, v0
        texldl r23, r23, s2
        add r21, r21, r23
        if_gt c44.y, r20.w
          mad r23.xy, r22, c112.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c112.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c113.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c113.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c114.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c114.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c115.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c115.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c116.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c116.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c117.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c117.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c118.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c118.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c119.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c119.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c120.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c120.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c121.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c121.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c122.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c122.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c123.xyyy, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mad r23.xy, r22, c123.zwww, v0
          texldl r23, r23, s2
          add r21, r21, r23
          mul r20.y, r20.y, c4.w
        endif
        mul r21, r21, r20.y
        mov r3, r21
        mov r4, r21
        mov r5, r21
        mov r6, r21
      endif
    endif
    mul r3.xyz, r3, r1.w
    mad r3.xyz, r7, r0.z, r3
    mad r3.xyz, r4, r1.w, r3
    mad r3.xyz, r5, r1.w, r3
    mad r3.xyz, r6, r1.w, r3
    mad r4.xyz, v0.yxyw, c5.x, c5.y
    mul r0.z, r4.y, c77.z
    mul r0.z, r0.y, r0.z
    mul r1.w, -r4.x, c77.w
    mul r1.w, r0.y, r1.w
    mul r5.xyz, r1.w, c73
    mad r5.xyz, r0.z, c72, r5
    mad r5.xyz, -r0.y, c74, r5
    add r5.xyz, r5, c75
    mul r0.y, -r5.z, c77.z
    rcp r0.y, r0.y
    mul r6.x, r5.x, r0.y
    mul r0.y, r5.z, c77.w
    rcp r0.y, r0.y
    mul r6.y, r5.y, r0.y
    add r0.yz, -r4, r6.xxyw
    rcp r20.x, c221.z
    mul r20.x, r20.x, c11.x
    mul r20.x, r20.x, c80.x
    min r20.x, r20.x, c4.w
    mul r0.yz, r0, r20.x
    mul r4.xy, r0.yzzw, c5.z
    texld r5, v0, s6
    add r1.w, r5.x, -c85.x
    mul r4.zw, r3.xyxy, c3.w
    mad r4.zw, v0.xyxy, c0.xyxy, r4
    texld r5, r4.zwzw, s5
    add r2.w, r5.x, c4.x
    mad r4.zw, r4.xyxy, r2.w, v0.xyxy
    mov r5.xyz, r3
    mov r2.w, c2.y
    mov r3.w, c2.y
    if_ne c222.w, r31.x
      rep i0
        mad r6.xy, r4, r3.w, r4.zwzw
        texldl r7, r6, s6
        add r5.w, r7.x, -c85.x
        cmp r5.w, r5.w, c2.w, c2.y
        texldl r6, r6, s2
        mad r5.xyz, r6, r5.w, r5
        add r2.w, r2.w, r5.w
        add r3.w, r3.w, c2.y
      endrep
    endif
    rcp r2.w, r2.w
    mul r0.yz, r0, c44.xxyw
    dp2add r0.y, r0.yzzw, r0.yzzw, c1.x
    rsq r0.y, r0.y
    rcp r0.y, r0.y
    mul r0.y, r0.y, c4.w
    add r0.x, r0.x, c2.y
    rcp r0.x, r0.x
    mul_sat r0.x, r0.y, r0.x
    mad r4.xyz, r5, r2.w, -r3
    mad r0.xyz, r0.x, r4, r3
    cmp r0.xyz, r1.w, r3, r0
    texld r1, c1.x, s4
    rcp r0.w, r1.x
    mul r0.w, r0.w, c81.y
    rcp r1.x, r0.w
    mul r1.x, r1.x, c81.x
    mad r1.xyz, r2, c66.x, -r1.x
    mul r2.xyz, r1, c81.z
    mul r2.xyz, r2, c2.x
    cmp r1.xyz, r1, r2, c1.x
    mad r0.xyz, r0, c66.x, r1
    mul r1.xyz, r0.w, r0
    dp3 r1.x, r1, c1.yzww
    mad r0.xyz, r0, r0.w, -r1.x
    mad r0.xyz, c82.x, r0, r1.x
    mul r0.w, r1.x, c84.w
    mul r1.yzw, r0.w, c84.xxyz
    mov_sat r2.x, r0.w
    mad r0.xyz, c84, -r0.w, r0
    mad r0.xyz, r2.x, r0, r1.yzww
    mul r0.xyz, r0, c83
    add r0.xyz, r0, r0
    mov_sat r1.x, r1.x
    add r0.w, -r8.y, c82.z
    pow r2.x, r1.x, r0.w
    mul r12, r0, r2.x
    max r12, r12, c1.x
    if_ne c222.z, r31.x
      mov r20, c10
      add r21, r12, -c5.z
      cmp r22, r21, c2.w, c2.y
      lrp r23, r22, r20.x, r20.y
      pow r24.x, r12.x, r23.x
      pow r24.y, r12.y, r23.y
      pow r24.z, r12.z, r23.z
      add r25, r24, -c5.z
      mad r25, r25, r20.z, r20.w
      lrp r12.xyz, r22, r24, r25
    endif
    
    
    //def c144, 0.00390625, 0.3, -0.5, 0 // 1/256, valor perceptivel, 
    
    // ...
    
    //dcl_2d s8
    //dcl_volume s9
    
    // ...
    
    // end shader
    //mov oC0.xyz, r12
    mov r3.xyz, r12
    mov oC0.w, c2.y
    
    mul r0.xy, v0.xy, c218.xy
    mov r0.z, c218.z    
    texld r1.xyz, r0.xyz, s9
    add r1, r1, c144.z
    mul r4, r1, c144.x
    add oC0, r3, r4
    
    
    
    

// approximately 467 instruction slots used (113 texture, 354 arithmetic)

